### ISSUE TITLE
Get-ItemProperty error on Server 2012R2

### ISSUE THREAD

**Issue by RevitXman** [tecnobabble/nessus_win_cred_test#11]
![Screen Shot 2021-07-16 at 10 40 43 AM](https://user-images.githubusercontent.com/16884947/125969141-fd6541bb-55e2-418b-8400-46285fa5f1ce.png)

![Screen Shot 2021-07-16 at 10 36 18 AM](https://user-images.githubusercontent.com/16884947/125969107-6f431e25-b118-4229-aa32-fd42c0839d9f.png)

**Comment by tecnobabble** [comment]
To do: not assume the ReleaseID property exists casue Windows something something.
